-- MySQL Script generated by MySQL Workbench
-- Tue Sep 21 14:30:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema midterm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `midterm` ;

-- -----------------------------------------------------
-- Schema midterm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `midterm` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `midterm` ;

-- -----------------------------------------------------
-- Table `midterm`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midterm`.`role` ;

CREATE TABLE IF NOT EXISTS `midterm`.`role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `midterm`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midterm`.`user` ;

CREATE TABLE IF NOT EXISTS `midterm`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `role_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKn82ha3ccdebhokx3a8fgdqeyy` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKn82ha3ccdebhokx3a8fgdqeyy`
    FOREIGN KEY (`role_id`)
    REFERENCES `midterm`.`role` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `midterm`.`account_holder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midterm`.`account_holder` ;

CREATE TABLE IF NOT EXISTS `midterm`.`account_holder` (
  `date_of_birth` DATE NOT NULL,
  `mailing_city` VARCHAR(255) NULL DEFAULT NULL,
  `mailing_country` VARCHAR(255) NULL DEFAULT NULL,
  `mailing_number` VARCHAR(255) NULL DEFAULT NULL,
  `mailing_street` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  `number` VARCHAR(255) NULL DEFAULT NULL,
  `street` VARCHAR(255) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK5tyfveeddp5dqy88r0yl3x5vw`
    FOREIGN KEY (`id`)
    REFERENCES `midterm`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `midterm`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midterm`.`account` ;

CREATE TABLE IF NOT EXISTS `midterm`.`account` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `balance_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `balance_currency` VARCHAR(255) NULL DEFAULT NULL,
  `creation_date` DATE NOT NULL,
  `owner_id` BIGINT NOT NULL,
  `second_owner_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKixnhhd03jk8j1c9q4qsafkeup` (`owner_id` ASC) VISIBLE,
  INDEX `FKg8thhn3spokk4qc6220py6gkw` (`second_owner_id` ASC) VISIBLE,
  CONSTRAINT `FKg8thhn3spokk4qc6220py6gkw`
    FOREIGN KEY (`second_owner_id`)
    REFERENCES `midterm`.`account_holder` (`id`),
  CONSTRAINT `FKixnhhd03jk8j1c9q4qsafkeup`
    FOREIGN KEY (`owner_id`)
    REFERENCES `midterm`.`account_holder` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `midterm`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midterm`.`admin` ;

CREATE TABLE IF NOT EXISTS `midterm`.`admin` (
  `id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK1ja8rua032fgnk9jmq7du3b3a`
    FOREIGN KEY (`id`)
    REFERENCES `midterm`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `midterm`.`checking_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midterm`.`checking_account` ;

CREATE TABLE IF NOT EXISTS `midterm`.`checking_account` (
  `min_balance_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `min_balance_currency` VARCHAR(255) NULL DEFAULT NULL,
  `maintenance_fee_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `maintenance_fee_currency` VARCHAR(255) NULL DEFAULT NULL,
  `penalty_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `penalty_currency` VARCHAR(255) NULL DEFAULT NULL,
  `secret_key` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NOT NULL,
  `id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKc7fxiw236f4kvag916rq4udds`
    FOREIGN KEY (`id`)
    REFERENCES `midterm`.`account` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `midterm`.`credit_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midterm`.`credit_card` ;

CREATE TABLE IF NOT EXISTS `midterm`.`credit_card` (
  `credit_limit_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `credit_limit_currency` VARCHAR(255) NULL DEFAULT NULL,
  `interest` DECIMAL(19,4) NULL DEFAULT NULL,
  `last_interest` DATE NULL DEFAULT NULL,
  `penalty_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `penalty_currency` VARCHAR(255) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK5nn2ykrc28pst4v0axopldeqv`
    FOREIGN KEY (`id`)
    REFERENCES `midterm`.`account` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `midterm`.`savings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midterm`.`savings` ;

CREATE TABLE IF NOT EXISTS `midterm`.`savings` (
  `interest` DECIMAL(19,4) NULL DEFAULT NULL,
  `last_interest` DATE NULL DEFAULT NULL,
  `min_balance_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `min_balance_currency` VARCHAR(255) NULL DEFAULT NULL,
  `penalty_amount` DECIMAL(19,2) NULL DEFAULT NULL,
  `penalty_currency` VARCHAR(255) NULL DEFAULT NULL,
  `secret_key` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NOT NULL,
  `id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKs02t0s57xrunyqosm96vrttin`
    FOREIGN KEY (`id`)
    REFERENCES `midterm`.`account` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `midterm`.`student_checking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midterm`.`student_checking` ;

CREATE TABLE IF NOT EXISTS `midterm`.`student_checking` (
  `secret_key` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NOT NULL,
  `id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKcw2ja1qwe1e6xhuj4e1o9jvy6`
    FOREIGN KEY (`id`)
    REFERENCES `midterm`.`account` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `midterm`.`third_party`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `midterm`.`third_party` ;

CREATE TABLE IF NOT EXISTS `midterm`.`third_party` (
  `hashed_key` VARCHAR(255) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKtcjpve90sq4j3esfvti8jbba2`
    FOREIGN KEY (`id`)
    REFERENCES `midterm`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
